### ISSUE TITLE
processAcceptHeaders() does not sort headers correctly on PHP 7

### ISSUE THREAD

**Issue by andrerom** [zetacomponents/MvcTools#11]
Sorting behaves slightly different on PHP 7, this turns up in places where code by luck worked from before. On of those cases can be observed in `ezcMvcHttpRequestParser::processAcceptHeaders()`, when no `;q=` parameter is provided, meaning all headers have priority of 1. the order will end up begin reversed of what client provided.

Examples from test cases:
```
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
     array (
-      0 => 'text/html',
-      1 => 'application/xhtml+xml',
+      0 => 'application/xhtml+xml',
+      1 => 'text/html',
       2 => 'application/xml',
       3 => '*/*',
     ),
      'charsets' => 
     array (
-      0 => 'UTF-8',
-      1 => '*',
+      0 => '*',
+      1 => 'UTF-8',

@@ @@
     array (
-      0 => 'gzip',
-      1 => ' deflate',
+      0 => ' deflate',
+      1 => 'gzip',
     ),
```

I didn't find a immediate solution to this, so opted to report instead of trying to fix it.

**Comment by derickr** [comment]
I can't reproduce this with the tests for MvcTools itself. Is there a test in there that fails? If not, can you make one?

**Comment by andrerom** [comment]
ATM no, but perhaps at a later point.
